Implemented sigmoid and log_sigmoid, Resolves #171
burn-rs/burn pull request #221
Opened 2023-03-10 16:41 UTC by h4rr9

implemented sigmoid and log_sigmoid, added tests to check for overflow

2023-03-10 18:12 UTC, nathanielsimard requested changes

2023-03-10 18:12 UTC, nathanielsimard commented on burn-tensor/src/tensor/activation/base.rs
> +/// Applies the softmax function.
typo: `softmax` => `sigmoid`

2023-03-10 18:12 UTC, nathanielsimard commented on burn-tensor/src/tensor/activation/base.rs
> +/// Applies the log softmax function.
same typo

2023-03-10 18:38 UTC, h4rr9 commented on burn-tensor/src/tensor/activation/base.rs
> +/// Applies the softmax function.
fixed the typo

2023-03-10 18:38 UTC, h4rr9 commented on burn-tensor/src/tensor/activation/base.rs
> +/// Applies the log softmax function.
fixed the typo

2023-03-11 00:02 UTC, nathanielsimard approved these changes

2023-03-11 00:03 UTC, merged