Matmul 2D Tiling
burn-rs/burn pull request #442
Opened 2023-06-27 16:21 UTC by louisfd

Matmul 2D Tiling

2023-06-27 16:54 UTC, nathanielsimard requested changes

2023-06-27 20:29 UTC, antimora requested changes
Overall looks good but lacks comments. I would encourage to add intention comments above any big blocks to guide the reader.

2023-06-27 20:29 UTC, antimora commented on burn-wgpu/src/kernel/matmul.rs
> +const T_N: usize = 8;
Could we add comments for each constant to signify what B_M stands for, e.g.? The names to short to know what they're.

2023-06-27 20:29 UTC, antimora commented on burn-wgpu/src/kernel/matmul.rs
> +    assert!(B_K * max(B_M, B_N) <= 8192, "B_K x B_M and B_K x B_N must be smaller or equal than 8192, otherwise shared memory limit will be busted. ");
Can we extract the magic number 8192 into a const with a name and comment?

2023-06-27 20:29 UTC, antimora commented on burn-wgpu/src/template/matmul_blocktiling_2d.wgsl
> +
For big blocks of code, can we add a brief intention comment? It's a good practice in general.

2023-06-27 20:29 UTC, antimora commented on burn-wgpu/src/template/matmul_blocktiling_2d.wgsl
> +
Same

2023-06-27 20:29 UTC, antimora commented on burn-wgpu/src/template/matmul_blocktiling_2d.wgsl
> +
Same

2023-06-28 15:57 UTC, antimora approved these changes
Looks much better with comments thanks for adding. 

There is one commented code you'd want to remove it if not needed.

2023-06-28 15:57 UTC, antimora commented on burn-wgpu/src/kernel/matmul.rs
> +// struct MatmulCaching;
Looks like this dead code is left out:  `// struct MatmulCaching;`

2023-06-28 20:38 UTC, nathanielsimard approved these changes
🚀🔥🎉

2023-06-28 20:48 UTC, merged