Update plot rendering from textplots-rs to termplot
burn-rs/burn pull request #485
Opened 2023-07-09 18:08 UTC by Poxxy

## Pull Request Template

### Checklist

- [X] Confirm that `run-checks.sh` has been executed.

### Related Issues/PRs

This solves issue here: https://github.com/burn-rs/burn/issues/211

### Changes

Rendering of plots relied on `textplot-rs` which has a couple of issues:

1. The dots were not rendering correctly, causing a confusion in what the graph is showing.
2. `textplot-rts` has a dependency with `nom` which causes a compilation warning when building `burn`

The changes made reflect the requirements for using `termplot`. The main two changes made:

1. Coloring is not an option for `termplot` so all references to color have been removed.
2. `termplot` uses `f64` values instead of `f32` values which were previously used. Conversions have been made where necessary.
3. `width` variable was of type `u32` but has been changed to `usize` to match `height`. Use of `usize` is better practice in this case as well.
4. Syntax has been modified as needed to work with `termplot`.

### Testing

Testing has been done by rendering plots for training data such as `mnist` example.

2023-07-09 18:09 UTC, Poxxy commented
Attached is an example rendering on my system which uses VSCode dark mode on Linux Mint.

![improved_rendering](https://github.com/burn-rs/burn/assets/41162160/e29c6725-1c7d-4b90-87a6-823e75b20d50)

2023-07-10 03:40 UTC, antimora commented
I can confirm no compilation warning. 

I have run your changes locally on Mac M1 via vscode's term, the dots still appear as before. So your term must have a nicer fonts that render the dots differently. Maybe there is a setting in the library to adjust this somehow so an average user can see the plots clearly.

Here is what I am seeing now: ![image](https://github.com/burn-rs/burn/assets/939125/9f272560-259f-4b42-b7a8-d9dd969c3931)

Also there are RED/BLUE labels in `cli.rs` that probably need to be updated since we don't have colors:

["  - {} RED: train | BLUE: valid \n{}",](https://github.com/Poxxy/burn/blob/0d17026a2d61ecd5f59bff74197ba0d466dccf07/burn-train/src/metric/dashboard/cli.rs#L140)

2023-07-10 15:28 UTC, nathanielsimard requested changes
It doesn't work with the text-accuracy example from my side, so maybe there is more work to be done before being merged.

2023-07-10 15:28 UTC, nathanielsimard commented on burn-train/src/metric/dashboard/plot.rs
> +            .set_y_label("Y-Axis: Accuracy")
The Y-Axis isn't always accuracy, it depends on the metric.

2023-07-12 16:08 UTC, closed without merging