Add functions to cast tensor to different kinds
burn-rs/burn pull request #530
Opened 2023-07-25 11:38 UTC by trfdeer

## Pull Request Template

### Checklist

- [x] Confirm that `run-checks.sh` has been executed.

### Related Issues/PRs

Related Issue: #487 

### Changes

1. Added `.int()` method to convert float tensors to integer kind.
2. Added `.float()` method to convert int tensors to float kind.

### Testing

Tested by manually creating and converting tensors.

2023-07-25 15:33 UTC, antimora commented
Great. Thank you. We will need some unit tests because we can accept the PR. 

Please see this recent PR for how to add a test: https://github.com/burn-rs/burn/pull/486/files

There are 3 parts: 

1. add test under tests/ops. Make sure the file name is `cast` and the macro on the top file includes the name: like this `#[burn_tensor_testgen::testgen(cast)]`
2. add the auto generated test here: burn-tensor/src/tests/mod.rs
3. expose the module here: burn-tensor/src/tests/ops/mod.rs

To test, you'll need to cd to burn-ndarray and run `cargo test`. The test will use burn-ndarray backend. `run-checks.sh` will test on all backends.

2023-07-26 13:45 UTC, nathanielsimard requested changes
A little change to the API before we can merge it. Thanks!

2023-07-26 13:45 UTC, nathanielsimard commented on burn-tensor/src/tensor/api/float.rs
> +    }
I would take ownership here and call `into_data`. In a following PR we should call a backend function where each backend can decide how they do the conversion. For instance, in this current implementation, the wgpu backend would need to allocate at least 3 new buffers, where 0 or 1 could have been allocated with proper casting.

2023-07-26 15:10 UTC, antimora approved these changes
Looks good. Thank you for your contribution.

2023-07-26 18:20 UTC, nathanielsimard approved these changes

2023-07-26 18:20 UTC, merged