Perf/wgpu/autotune
burn-rs/burn pull request #609
Opened 2023-08-08 19:39 UTC by louisfd

Added Autotune for matmul

2023-08-09 15:57 UTC, louisfd commented
I deactivated the default on the autotune compile because it makes the wgpu test suite extremely slow. 
We should inspect the cause of the slowness before putting it to default. I'll open an issue. 
Nevertheless, I think this PR can be merged as it does not slow down the test suite if the flag is not set.

2023-08-09 20:34 UTC, nathanielsimard requested changes

2023-08-09 20:34 UTC, nathanielsimard commented on burn-wgpu/src/benchmark.rs
> +            // );
We should just delete this.

2023-08-09 20:34 UTC, nathanielsimard commented on burn-wgpu/src/benchmark.rs
> +        // Self: Sized,
Dead code

2023-08-09 20:34 UTC, nathanielsimard commented on burn-wgpu/src/context/base.rs
> +        let template_id = ComputeKey::Static(TypeId::of::<K>());
Let's rename `ComputeKey` to `TemplateKey`

2023-08-09 20:34 UTC, nathanielsimard commented on burn-wgpu/src/kernel/matmul/tune.rs
> +        vec![Vec::from(shape_lhs.dims), Vec::from(shape_rhs.dims)],
I think there is a problem, we will recompute the benchmarks for tensors of different rank. we should only add M, N and K in the list of usize.

2023-08-09 20:34 UTC, nathanielsimard commented on burn-wgpu/src/kernel/matmul/tune.rs
> +                    10,
Should be 5 I think.

2023-08-09 20:34 UTC, nathanielsimard commented on burn-wgpu/src/ops/float_ops.rs
> +        return kernel::matmul::tune::<G, F, D>(lhs, rhs);
I think we should keep the autotune default, but only run if not in test mode.

`#[cfg(all(feature = "autotune", not(test))]`

2023-08-15 14:22 UTC, nathanielsimard approved these changes

2023-08-15 14:22 UTC, nathanielsimard commented on burn-wgpu/src/kernel/matmul/tune.rs
> +        format!("matmul {}", E::type_name()),
Mettre device dans id.

2023-08-15 15:26 UTC, merged