Training metrics
burn-rs/burn pull request #647
Opened 2023-08-16 13:10 UTC by Elazrod56

## Pull Request Template

### Checklist

- [x] Confirm that `run-checks` script has been executed.

### Related Issues/PRs

This PR partially solves issue #544, which asked for more training metrics.  

#### Metrics requested and successfully implemented
- General CPU utilization metric (use percentage)
- General memory (RAM + swap) utilization metric (use percentage)

#### Metrics requested but not implemented, and the reason why I couldn't implement it
- Top-k accuracy: I am not familiar with deep learning, and couldn't understand this metric properly
- General GPU utilization: My computer only has an AMD APU, no GPU.
- General GPU memory usage: My computer only has an AMD APU, no GPU.
- Precision Recall: I am not familiar with deep learning, and couldn't understand this metric properly
- AUC - ROC: I am not familiar with deep learning, and couldn't understand this metric properly
- BLEU score: I am not familiar with deep learning, and couldn't understand this metric properly
- ROUGE score: I am not familiar with deep learning, and couldn't understand this metric properly

#### Metrics not requested yet implemented
- CPU Temperature
- GPU Temperature

### Changes

In issue #544, it has been said that it would be great to have more training metrics. So I have added the metrics that I was skilled enough to add and that I could properly test on my hardware.

### Testing

I actually started developing metrics in separate cargo projects, and printed the data to the console.
To check the accuracy of this data, I have used a system tray that I have on my system (see attachment) which shows me hardware info (CPU use percentage, CPU temp, RAM and swap use percentage). Then I simply compared the data, and saw it was accurate.  
  
This is the system tray. From left to right: CPU use, CPU temp, RAM use (swap is displayed once I click it, date/time and battery)
![system_tray_pr645](https://github.com/burn-rs/burn/assets/111651813/c091bab1-74ca-48e4-a27d-fe860dfaf811)  
  
Note: since my "GPU" is actually an APU, my GPU temp is roughly the same as my CPU temp, this is how I tested this metric.

Once I knew that my metric was accurate, I copied the code to BURN and adapted the Metric trait for my data type. And voilà, a new metric.  
I have mainly "copied" what I have seen in the CUDA metric, because I didn't know much about the BURN framework.

2023-08-16 14:24 UTC, nathanielsimard requested changes
I think there are few possible improvements. Thanks for implementing those metrics, hardware usage is pretty useful information when training deep learning models!

2023-08-20 11:07 UTC, Elazrod56 commented
Hi, I've addressed the changes requested. 
In cpu_temp.rs, I've decided to change crates because there was no way to accurately and reliably get the cpu temperature with sysinfo, so I went on with systemstat. I've kept sysinfo for the other metrics.

Let me know if there are any changes that are worth doing

2023-08-20 16:00 UTC, antimora commented
Formatting step in CI is failing.

2023-08-20 18:41 UTC, Elazrod56 commented
What should I do ? `cargo fmt` ?

2023-08-20 18:45 UTC, antimora commented
> What should I do ? `cargo fmt` ?

To fix it, yes. If you have clippy errors, you can `cargo clippy --fix` as well.

2023-08-20 18:48 UTC, Elazrod56 commented
Okay, I'll do it when I get back from work

2023-08-21 00:11 UTC, nathanielsimard requested changes
I have the same comment on all metrics, when it's fixed I think we can merge.

2023-08-21 00:11 UTC, nathanielsimard commented on burn-train/src/metric/cpu_temp.rs
> +        let mut cpu_temp = CpuTemp::new();
Instead of creating a new struct, we should just mutate the current one.

2023-08-21 00:11 UTC, nathanielsimard commented on burn-train/src/metric/cpu_use.rs
> +        let mut cpu_use = CpuUse::new();
Instead of creating a new struct, we should just mutate the current one.

2023-08-21 00:11 UTC, nathanielsimard commented on burn-train/src/metric/gpu_temp.rs
> +        let mut gpu_temp = GpuTemp::new();
Instead of creating a new struct, we should just mutate the current one.

2023-08-21 00:11 UTC, nathanielsimard commented on burn-train/src/metric/memory_use.rs
> +        let mut memory_use = MemoryUse::new();
Instead of creating a new struct, we should just mutate the current one.

2023-08-21 18:13 UTC, nathanielsimard approved these changes

2023-08-21 18:13 UTC, merged