Path type
burn-rs/burn pull request #699
Opened 2023-08-25 20:11 UTC by asukaminato0721

## Pull Request Template

### Checklist

- [x] Confirm that `run-checks` script has been executed.

### Related Issues/PRs

https://github.com/burn-rs/burn/issues/698

### Changes

`&str` to `AsRef<Path>`

### Testing

_Describe how these changes have been tested._

2023-08-26 19:59 UTC, antimora commented
Thank you for your PR.

Build is failing. Please, rerun `run-checks` from the root. There is an example crate is failing to build.

2023-08-26 21:57 UTC, nathanielsimard requested changes
I would also receive `P: AsRef<std::path::Path>` for the `load` function. Maybe you need to change the `to_string` to something like this: https://doc.rust-lang.org/std/path/struct.Path.html#method.to_string_lossy

2023-08-27 04:01 UTC, antimora approved these changes
LGTM

2023-08-27 13:17 UTC, nathanielsimard approved these changes

2023-08-27 13:17 UTC, merged