Cross Entropy with label smoothing and weights.
burn-rs/burn pull request #755
Opened 2023-09-02 14:55 UTC by ArvidHammarlund

## Pull Request Template

### Checklist

- [ X] Confirm that `run-checks` script has been executed.

### Changes

Added label smoothing and weights to cross entropy.

### Testing

Label smoothing forces a different implementation of the loss calculation, so those are tested against the default implementation. Weights are unit tested against a manual implementation.

2023-09-02 15:50 UTC, nathanielsimard requested changes
Thanks @ArvidHammarlund for the PR; it's a nice improvement of the current implementation.

Since the loss is starting to get more complicated with more options, I would make it a module by adding the `Module` derive. I would also add config, similar to other modules, which will avoid having to manually implement builder methods.

We could keep a `default` function to create the Loss:

```rust
impl Default for CrossEntropyLoss {
    fn default() -> Self {
        CrossEntropyLossConfig::new().init()
    }
}
```

But when using weights tensors, it's probably better to initialize the loss function within our module. By implementing the module trait, we will ensure that the weights are always on the same device as the other weights, which isn't checked with the current implementation.

2023-09-02 16:01 UTC, ArvidHammarlund commented
Good points! I will try to make the changes later today.

2023-09-02 20:07 UTC, ArvidHammarlund commented
I have now made the changes. I also added a binary version, and made it possible to use multiple pad tokens as well.

2023-09-03 12:46 UTC, nathanielsimard reviewed
Very good job 🙏! I'm unsure if we should mix binary cross entropy with the normal cross entropy, curious to hear your thoughts!

2023-09-03 12:46 UTC, nathanielsimard commented on burn-core/src/nn/loss/cross_entropy.rs
> +        let logits = logits.slice([0..batch_size, 0..1]).reshape([batch_size]);
I'm not sure we need the `slice`, just the reshape should do the job; if the logits have more than just one element per batch, I think it's better to panic than to train with bugs.

2023-09-03 12:46 UTC, nathanielsimard commented on burn-core/src/nn/loss/cross_entropy.rs
> +    binary: bool,
I think we should support binary cross entropy with another module. The forward pass should have a different signature (only tensors of rank 1), the config options won't support padding and the weights config could be `[usize; 2]`. What do your think?

2023-09-03 12:46 UTC, nathanielsimard commented on burn-core/src/nn/loss/cross_entropy.rs
> +    weights: Option<Tensor<B, 1>>,
I would put the weights public, so we could print them, or use a tensor from someplace else.

2023-09-03 14:47 UTC, ArvidHammarlund commented
I believe moving out the binary version would be an easy compile time check win (logits of dimension = 1), which is good; the only downside I could think of is that docs.rs can grow quite daunting to discern when codegen generate three additional items for every struct - maybe I could move record and recordItem to a subdirectory like nn::loss::records? Btw, should I make run time assertions for every forward pass, checking if e.g. no label are assigned an int greater than weights tensor length, or would that cause to high overhead?

2023-09-03 16:13 UTC, nathanielsimard commented
> I believe moving out the binary version would be an easy compile time check win (logits of dimension = 1), which is good; the only downside I could think of is that docs.rs can grow quite daunting to discern when codegen generate three additional items for every struct - maybe I could move record and recordItem to a subdirectory like nn::loss::records? Btw, should I make run time assertions for every forward pass, checking if e.g. no label are assigned an int greater than weights tensor length, or would that cause too high overhead?

1. About the docs, since the code is generated, the solution would be in `burn-derive`, so behond the scope of this PR.
2. Checks are very cheap at that level, so it won't be a performance problem.

2023-09-03 16:15 UTC, ArvidHammarlund commented
Ok. I am doing the revisions now!

2023-09-04 09:01 UTC, ArvidHammarlund commented
The smoothing parameter makes some buffers time out on WPGU backend, so this PR shouldn't be approved yet!

2023-09-04 13:24 UTC, nathanielsimard requested changes
Some checks are too expensive to call during the forward pass. I would also move the binary cross entropy loss into another file `binary_cross_entropy.rs`. 

I think you commited the file `script/run-checks` is it a mistake?

2023-09-04 13:24 UTC, nathanielsimard commented on burn-core/src/nn/loss/cross_entropy.rs
> +        );
I would remove that assertion, asserting shapes is fine, but when it comes to the underlying tensor data, it's normally too slow.

2023-09-04 13:24 UTC, nathanielsimard commented on burn-core/src/nn/loss/cross_entropy.rs
> +    pub weights: Option<Vec<f32>>,
Can it be `[f32; 2]` instead?

2023-09-04 13:57 UTC, ArvidHammarlund commented
I made the changes now. 

> I think you commited the file `script/run-checks` is it a mistake?

Yes, I thought that was due to me adding units tests?  But I probably shouldn't use git add -A in such large code bases, anyways.

2023-09-04 15:12 UTC, ArvidHammarlund commented
Cargo says that the slice method with an array as index is not valid syntax for me. Is there something I am missing?

2023-09-04 15:30 UTC, nathanielsimard commented
> Cargo says that the slice method with an array as index is not valid syntax for me. Is there something I am missing?

I think you have to allow that warning in the project: `#![allow(clippy::single-range-in-vec-init)]`

2023-09-05 00:20 UTC, nathanielsimard approved these changes

2023-09-05 00:20 UTC, nathanielsimard commented
@ArvidHammarlund I'll fix the CI 😅

2023-09-05 00:20 UTC, merged