wip: Refactor/burn benchmark
burn-rs/burn pull request #829
Opened 2023-09-25 18:05 UTC by louisfd

### Changes

Refactored benchmarks to make them backend agnostic. 
Warning: it is now impossible to run different versions of the same operation (like the 6 wgpu matmul versions), I am yet to figure out a way to do so, so you could consider this a work in progress

### Testing

Locally ran `cargo bench --features <backend>` for each backend

2023-09-26 16:43 UTC, louisfd commented
@nathanielsimard 
Not wip anymore, wgpu matmuls are back. You can review

2023-09-26 19:48 UTC, nathanielsimard requested changes

2023-09-26 19:48 UTC, nathanielsimard commented on backend-comparison/Cargo.toml
> +repository = "https://github.com/burn-rs/burn/tree/main/benchmark"
https://github.com/burn-rs/burn/tree/main/backend-comparison

2023-09-26 19:48 UTC, nathanielsimard commented on burn-wgpu/src/benchmark/matmul.rs
> +use std::marker::PhantomData;
The benchmark code should not be under `src`.

2023-09-28 13:28 UTC, nathanielsimard approved these changes

2023-09-28 13:38 UTC, merged