wgpu: Yet another (faster) matmul
burn-rs/burn pull request #836
Opened 2023-09-29 19:16 UTC by louisfd

New matmul kernel that leverages WGSL's vec4 data struct. 
It's considerably faster on my laptop. You can check its performance by running `cargo bench` within the burn-wgpu crate. 
It's the one called "Tiling2DMatmulVec4Primitive"

2023-09-29 20:02 UTC, nathanielsimard requested changes

2023-09-29 20:02 UTC, nathanielsimard commented on burn-wgpu/src/kernel/matmul/utils.rs
> +        println!("{:?}", z.to_data());
Remaining  println!

2023-09-30 13:41 UTC, louisfd commented on burn-wgpu/src/kernel/matmul/utils.rs
> +        println!("{:?}", z.to_data());
Classic

2023-10-02 18:05 UTC, nathanielsimard approved these changes

2023-10-02 18:05 UTC, merged